services:

  db:
    image: postgres:15
    container_name: daw9_db
    environment:
      - POSTGRES_DB=daw9_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
    ports:
      - "5433:5432"
    networks:
      - daw9-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d daw9_db" ]
      interval: 5s
      timeout: 5s
      retries: 5

  api-service:
    build: ./backEnd
    container_name: daw9_api
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/daw9_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=admin
    depends_on:
      db:
        condition: service_healthy
    networks:
      - daw9-network
    volumes:
      - ./backEnd/uploads:/app/uploads

  frontend:
    build: ./frontEnd
    container_name: daw9_front
    ports:
      - "4200:80"
    depends_on:
      - api-service
    networks:
      - daw9-network

volumes:
  db_data:
networks:
  daw9-network:
    driver: bridge
